<?php

$lang = array(
	'privacy_policy'				=>	"<p><span class='bodyTextDarkBold'>1. Introduction</span> <br>".
															"The purpose of this policy is to explain how BookSift collects, protects, ".
															"and uses personal data. BookSift is committed to ensuring that any personal ".
															"data supplied by its customers or is otherwise generated by its business ".
															"activities is collected and processed fairly and lawfully. ".
															"<p><span class='bodyTextDarkBold'>2. What types of personal data ".
															"does BookSift collect? </span><br>BookSift needs certain personal ".
															"data to enable it to provide its products and services to its ".
															"customers and end users. The personal data collected will generally ".
															"include: name, postal address, telephone and fax numbers, e-mail ".
															"addresses. BookSift also has access to personal data that is generated ".
															"over the BookSift network including IP and email addresses for incoming ".
															"and outgoing data and network usage data.<br>In certain circumstances ".
															"BookSift may also collect financial information about BookSift customers ".
															"and end users from third parties to enable BookSift to assess its risks ".
															"in granting credit terms and contact information about individuals and ".
															"organisations BookSift considers may be interested in BookSift products ".
															"and services. </p>".
															"<p><span class='bodyTextDarkBold'>3. How does BookSift obtain personal ".
															"data?</span> <br>BookSift obtains personal data in a number of ways ".
															"including from bookings placed by customers and end users (whether by ".
															"telephone, fax or email or by application form); from enquiries made ".
															"by existing customers and potential customers, (including information ".
															"gathered at marketing events and via the BookSift website);from third ".
															"party list brokers; from resellers who pass on personal data to BookSift ".
															"about end users; and directly from the BookSift network. </p>".
															"<p class='bodyTextDarkBold'>4. How does BookSift use the personal data it ".
															"holds? </p><p><span class='bodyTextDarkBold'>4.1 Providing and improving ".
															"the BookSift service</span> <br>Most of BookSift use of personal data is ".
															"necessary to enable it to provide a service to its customers and its end ".
															"users, including booking processing, support services as well as for ".
															"invoicing and in order to answer general customer enquiries. In addition, ".
															"BookSift may also use personal data to improve on the level and type of ".
															"service BookSift offers to its customers. As part of this interest in ".
															"improving the service provided BookSiftmay process personal data for ".
															"the purposes of sales analysis and customer usage statistics. </p>".
															"<p><span class='bodyTextDarkBold'>4.2 Direct marketing</span> ".
															"<br>BookSift may from time to time inform its customers, end users ".
															"and potential customers about BookSift and BookSift affiliate products ".
															"and services and other information BookSift feels may be of interest.<br>".
															"Customers and other recipients of information from BookSift may indicate at ".
															"the time they create an account whether or not they wish to receive such ".
															"information or at any later time by simply contacting BookSift as indicated ".
															"in paragraph 9 below. </p><p><span class='bodyTextDarkBold'>5. Does BookSift ".
															"transfer personal data overseas?</span> <br>As BookSift is part of a global ".
															"organisation with local operating companies in a number of countries ".
															"worldwide, to fulfil its customer service obligations it is necessary ".
															"for BookSift to transfer and process personal data outside the country ".
															"in which the personal data is collected. This will include transfers to ".
															"BookSift affiliates based in the United States. Prior to making any such ".
															"transfer BookSift will put in place security procedures and firewalls ".
															"designed to prevent unauthorised use of or access to personal data. </p>".
															"<p><span class='bodyTextDarkBold'>6. To whom does BookSift disclose personal ".
															"data? </span><br>BookSift will pass personal data within its internal ".
															"departments in order to fulfil sales and support obligations as well as ".
															"to finance departments to enable invoicing.<br>As a general rule, BookSift ".
															"does not disclose personal data to unaffiliated third parties except where ".
															"customer consent has been obtained or where BookSift is under an ".
															"obligation by law to disclose personal data. </p>".
															"<p><span class='bodyTextDarkBold'>7. How does BookSift protect the personal ".
															"data it holds?</span> <br>BookSift takes customer confidentiality and security ".
															"very seriously. BookSift uses industry standard encryption to secure all ".
															"sensitive client and end user data its stores.<br>BookSift has implemented ".
															"appropriate internal security procedures that restrict access to and ".
															"disclosure of personal data within BookSift. These procedures will be ".
															"reviewed from time to time to determine whether they are being complied ".
															"with and are effective.<br>BookSift will also actively investigate and ".
															"cooperate with law enforcement agencies any allegations of abuse or ".
															"violation of system or network security as set out in the applicable ".
															"BookSift Acceptable Use Policy. </p>".
															"<p><span class='bodyTextDarkBold'>8. Customers rights</span> <br>The ".
															"law in certain jurisdictions (including countries within the European ".
															"Economic Area) gives individuals whose personal data is held by BookSift ".
															"specific rights to access and rectify personal data held about them. ".
															"These include the right to: </p><p><span class='bodyTextDarkBold'>8.1</span> <br>".
															"Obtain from BookSift, for a prescribed fee, confirmation that personal ".
															"data is held, as well as a written description of such personal data, ".
															"the purpose(s) for which it is being used, the source(s) of the personal ".
															"data and details of any recipients; </p>".
															"<p><span class='bodyTextDarkBold'>8.2 </span><br>Request the deletion or ".
															"rectification of personal data which is inaccurate; and </p>".
															"<p><span class='bodyTextDarkBold'>8.3</span> <br>As explained in paragraph ".
															"4.2 above to object to any unsolicited information sent by BookSift ".
															"regarding promotions or new products and services. </p>".
															"<p><span class='bodyTextDarkBold'>9. Contact Details</span> <br>".
															"If any individual wishes to contact BookSift regarding the personal data ".
															"held about them or has any other question about BookSift data privacy ".
															"procedures, they should direct an email to privacy(at)booksift(dot)com or send ".
															"a letter to the direction of &quot;BookSift&quot; at BookSift office. </p>".
															"<p><span class='bodyTextDarkBold'>10. Policy updates</span> <br>As part of ".
															"BookSift commitment to compliance with data privacy requirements, and to ".
															"reflect changes in BookSift operating procedures, BookSift may update the ".
															"terms of this policy from time to time, and will post the revised policy ".
															"at BookSift Acceptable Use Policy.</p>",
);

?>